language: node_js
node_js:
- "9.11"
dist: trusty
sudo: false

cache:
  directories:
  - node_modules

#addons:
#  chrome: stable

script:
#- npm run lint
#- npm run test:headless
- npm run buildci
#- xvfb-run npm run e2e