## Build Specification Reference for AWS CodeBuild  https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
## Defintion of Image that is used for build: https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/nodejs/10.14.1
## nice pic https://stelligent.com/2017/03/09/using-parameter-store-with-aws-codepipeline/ about process
## https://aws.amazon.com/de/blogs/mt/use-parameter-store-to-securely-access-secrets-and-config-data-in-aws-codedeploy/
version: 0.2

env:
    ## DEFAULT ENV VARIABLES: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
    ## CODEBUILD_RESOLVED_SOURCE_VERSION,CODEBUILD_INITIATOR
    variables:
        APP_NAME: "yummy"
        BUILD_ENV: "prod"
    #parameter-store vars are in the format /[stage]/[repo]/[branch]/[eyecatcher]/key
    parameter-store: #see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax
        bucketRegion: "/yummy/prod/bucketRegion"
        region: "/yummy/prod/region"
        identityPoolId: "/yummy/prod/identityPoolId"
        userPoolId: "/yummy/prod/userPoolId"
        clientId: "/yummy/prod/clientId"
        ddbTableNamePrefix: "/yummy/prod/ddbTableNamePrefix"
        bucketNamePrefix: "/yummy/prod/bucketNamePrefix"
        mapboxAccessToken: "/yummy/prod/mapboxAccessToken"
        apiGatewayInvokeUrl: "/yummy/prod/apiGatewayInvokeUrl"
        webappBucketS3: "/yummy/prod/webappBucketS3"

phases:
    install:
        commands:
        # Install Yarn Package Manager (Replace the commands below if you using NPM).
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -y
        - sudo apt-get install -y yarn
        # Install Angular CLI, If you are not using Angular 6, install angular/cli@1.7.0 or lower, confirm by running ng -v inside your project folder
        - yarn global add @angular/cli@6.0.8
        # Install node dependancies, ignore engine b/c of node 10 vs node 9 issues
        - yarn install --ignore-engines

    build:
        commands:
        # Builds Angular application. You can also build using custom environment here like mock or staging
        - echo Build for ${BUILD_ENV} started
        - touch "./src/environments/environment.ts"
        - envsubst <"./src/environments/environment.ts.tmpl"  > "./src/environments/environment.prod.ts"
        - cat ./src/environments/environment.prod.ts
        - yarn buildci

    post_build:
        commands:
        # Clear S3 bucket.
        - echo About to deploy to s3://${S3_BUCKET}
        ## e.g. aws-cli/1.16.69 Python/3.4.3 Linux/4.14.77-70.59.amzn1.x86_64 exec-env/AWS_ECS_EC2 botocore/1.12.59
        - aws --version || echo aws not installed
        - aws s3 sync ./dist/ ${webappBucketS3} --region ${bucketRegion} --delete --size-only
        ## size-only is not good for index.html as the size may not change but the checksum of included scripts does
        - aws s3 cp ./dist/index.html ${webappBucketS3}/index.html --region ${bucketRegion}
        #- echo Build completed on `date`

#artifacts:
#    files:
#        - '**/*'
#    discard-paths: yes
 #   base-directory: 'dist*'
